2023-11-21 19:12:16,311 INFO    MainThread:24276 [wandb_setup.py:_flush():76] Current SDK version is 0.16.0
2023-11-21 19:12:16,311 INFO    MainThread:24276 [wandb_setup.py:_flush():76] Configure stats pid to 24276
2023-11-21 19:12:16,311 INFO    MainThread:24276 [wandb_setup.py:_flush():76] Loading settings from /home/mitul/.config/wandb/settings
2023-11-21 19:12:16,312 INFO    MainThread:24276 [wandb_setup.py:_flush():76] Loading settings from /home/mitul/Downloads/penalty-shot-project/wandb/settings
2023-11-21 19:12:16,312 INFO    MainThread:24276 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-11-21 19:12:16,312 INFO    MainThread:24276 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-11-21 19:12:16,312 INFO    MainThread:24276 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'utils/train.py', 'program_abspath': '/home/mitul/Downloads/penalty-shot-project/utils/train.py', 'program': './utils/train.py'}
2023-11-21 19:12:16,312 INFO    MainThread:24276 [wandb_init.py:_log_setup():524] Logging user logs to /home/mitul/Downloads/penalty-shot-project/wandb/run-20231121_191216-w0oxhlzp/logs/debug.log
2023-11-21 19:12:16,312 INFO    MainThread:24276 [wandb_init.py:_log_setup():525] Logging internal logs to /home/mitul/Downloads/penalty-shot-project/wandb/run-20231121_191216-w0oxhlzp/logs/debug-internal.log
2023-11-21 19:12:16,312 INFO    MainThread:24276 [wandb_init.py:init():564] calling init triggers
2023-11-21 19:12:16,312 INFO    MainThread:24276 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2023-11-21 19:12:16,312 INFO    MainThread:24276 [wandb_init.py:init():614] starting backend
2023-11-21 19:12:16,312 INFO    MainThread:24276 [wandb_init.py:init():618] setting up manager
2023-11-21 19:12:16,314 INFO    MainThread:24276 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2023-11-21 19:12:16,315 INFO    MainThread:24276 [wandb_init.py:init():624] backend started and connected
2023-11-21 19:12:16,321 INFO    MainThread:24276 [wandb_init.py:init():716] updated telemetry
2023-11-21 19:12:16,334 INFO    MainThread:24276 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2023-11-21 19:12:20,369 ERROR   MainThread:24276 [wandb_init.py:init():775] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-11-21 19:12:21,082 ERROR   MainThread:24276 [wandb_init.py:init():1184] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "/home/mitul/Downloads/penalty-shot-project/venv/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 1166, in init
    run = wi.init()
  File "/home/mitul/Downloads/penalty-shot-project/venv/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 781, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-11-21 19:12:22,087 WARNING MsgRouterThr:24276 [router.py:message_loop():77] message_loop has been closed
